import type { NextApiRequest, NextApiResponse } from "next";
import { NextResponse, NextRequest } from "next/server";

let cache: any[] = [];

const listings: any[] = [
	{
		title: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
		description:
			"Sony's flagship high-resolution-kamera med 61mp og 10-bit video-specs.\n\nAnmeldelse:\nhttps://www.youtube.com/watch?v=TqZk1zW2i1U\n\nSkriv for spørgsmål!\n\n5x Sony NP-FZ100 battery\n1x Sony A7R V\n1x LEXAR CFExpress 160GB-memory card\n1x Sony FE 24-70mm f2.8 G Master\n1x Sony FE 35mm f2.8 G Master\n1x Sony FE 20mm F1.8 G\n",
		price: 1000,
		priceExclVat: 800,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "rswuYE-4Pp5dCmv-J65dtw",
		image: "https://images.wedio.com/images/listing_images/images/1982657/medium/PSHOT-SONY-A7R-V-TOP-640PX.JPG",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/713796-sony-a7r-v-megapixel-beast-til-stills-og-8k-video-med-tre-objektiver",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"portraits",
			"astrophotography",
			"landscape",
			"birding",
			"food",
			"product",
			"documentary",
			"journalism",
			"instagram",
			"vlogging",
			"indoors",
			"outside",
		],
		productionType: "global-production-type-still-and-video",
		type: ["normal", "auto", "wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony NP-FZ100 battery",
			"Sony A7R V",
			"LEXAR CFExpress 160GB-memory card",
			"Sony FE 24-70mm f2.8 G Master",
			"Sony FE 35mm f2.8 G Master",
			"Sony FE 20mm F1.8 G",
		],
		_geoloc: {
			lat: 55.6761,
			lng: 12.5683,
		},
		city: "Copenhagen",
		author: {
			id: "rswuYE-4Pp5dCmv-J65dtw",
			name: "gemmergemmer",
			username: "gemmergemmer",
			image: "https://images.wedio.com/images/people/images/rswuYE-4Pp5dCmv-J65dtw/thumb/_DSC7301.jpg",
			country: "DK",
			vatVerified: true,
			reviews: 74,
			isPrime: false,
			feedback: 5,
		},
		objectID: "713796",
		_highlightResult: {
			title: {
				value: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony NP-FZ100 battery",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony A7R V",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR CFExpress 160GB-memory card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-70mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 35mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 20mm F1.8 G",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "gemmergemmer",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
		description:
			"Please ask for availability before booking.\n\nWhat's Included:\n\n- 1 * Canon Canon EOS R6 II Body\n- 2 * LP-E6NH Batteries\n- 1 * Battery Charger\n- 1 * Canon Camera Sling Strap\n- 2 * Lexar 256GB UHS-II Memory Cards\n- 1 * Camera Backpack",
		price: 29,
		priceExclVat: 24.166656,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "Mxvv6lya9KY_hxKLwu7vtg",
		image: "https://images.wedio.com/images/listing_images/images/1971255/medium/1.-Body-Only.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: true,
		offerShipping: true,
		offerFreeShipping: false,
		offerPickup: true,
		offerBuyNow: false,
		offerMakeOffer: true,
		gearCondition: "good",
		url: "https://www.wedio.com/listings/708430-canon-eos-r6-ii-body-only-2-batteries-2-256gb-uhs-ii-sd-cards",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: [
			" Canon EOS R6 II",
			"LP-E6NH",
			"Lexar 256GB UHS-II SD Card",
			"Canon EOS R6",
		],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "Mxvv6lya9KY_hxKLwu7vtg",
			name: "GeekyGain",
			username: "geekygain",
			image: "https://images.wedio.com/images/people/images/Mxvv6lya9KY_hxKLwu7vtg/thumb/GG-Logo-Black-(TM).png",
			country: "GB",
			vatVerified: true,
			reviews: 3,
			isPrime: false,
			feedback: 5,
		},
		objectID: "708430",
		_highlightResult: {
			title: {
				value: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: " Canon EOS R6 II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LP-E6NH",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Lexar 256GB UHS-II SD Card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R6",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "geekygain",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Blackmagic Studio Camera 4K Pro Body & Extras | BMSC MFT Mount",
		description:
			'👋🏻 Hello everyone!\n🚨 Please message for availability before booking.\n\n📍 Locations available for collection/returns: Herne Hill, Elephant and Castle, Farrington, Liverpool Street, Shoreditch, Stratford, Royal Wharf/Royal Victoria.\n☎️ Contact number to be given after booking confirmation.\n\n📮 Bundle Includes:\n▫️ Blackmagic Studio Camera 4K Pro\n▫️ Blackmagic baseplate + 6" dovetail\n▫️ x1 1TB SSD\n▫️ x1 1M thunderbolt cable\n▫️ x1 3M Ethernet Cable\n▫️ ×1 HDMI 4K60p 10ft braided cables\n▫️ DC to D-Tap braided power cable \n▫️ V-Mount battery\n▫️ V-Mount battery plate\n\n⏱️ 3 days booking = Pay for 2 days\n⏱️ 1 week booking = Pay for 4 days\n\n👍🏻 I care about offering the best quality for my customers and will make sure before departure and arrival that everything is in great condition.\n🪪 ID Required.\n\n📩 Any questions, feel free to get in touch!',
		price: 80,
		priceExclVat: 80,
		buyPrice: 1200,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "Qrv0SZvez0eL6tmoMJrbXA",
		image: "https://images.wedio.com/images/listing_images/images/1984087/medium/Fat-Llama-2---BMSC-4K-Pro-Body--Extras.png",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: true,
		offerShipping: true,
		offerFreeShipping: false,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: false,
		gearCondition: "like-new",
		url: "https://www.wedio.com/listings/714200-blackmagic-studio-camera-4k-pro-body-extras-bmsc-mft-mount",
		categories: ["1", "2"],
		goodFor: [
			"cinematography",
			"live_streaming",
			"astrophotography",
			"landscape",
			"birding",
			"product",
			"sports",
			"interviews",
			"documentary",
			"concert",
			"journalism",
			"music_videos",
			"skiing",
			"large_group",
			"indoors",
			"outside",
			"podcast",
			"other",
		],
		productionType: "global-production-type-video",
		items: ["Blackmagic Studio Camera 4K Pro", "Extras"],
		_geoloc: [
			{
				lat: 51.494,
				lng: -0.0992029,
			},
			{
				lat: 51.5183,
				lng: -0.0814556,
			},
			{
				lat: 51.5083,
				lng: 0.0147197,
			},
			{
				lat: 51.547,
				lng: -0.0078202,
			},
			{
				lat: 51.5203,
				lng: -0.104224,
			},
			{
				lat: 51.4632,
				lng: -0.100111,
			},
		],
		city: "London",
		author: {
			id: "Qrv0SZvez0eL6tmoMJrbXA",
			name: "Pop",
			username: "pop",
			image: "https://images.wedio.com/images/people/images/Qrv0SZvez0eL6tmoMJrbXA/thumb/POP-Icon-(Black).png",
			country: "GB",
			vatVerified: false,
			reviews: 6,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714200",
		_highlightResult: {
			title: {
				value: "Blackmagic Studio Camera 4K Pro Body & Extras | BMSC MFT Mount",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Blackmagic Studio Camera 4K Pro",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Extras",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "pop",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS C300 MK III",
		description:
			"Canon C300 III body only. THE KIT DOES NOT ICLUDE LENS.\n\nPlease feel free to contact for a customise package or see other listing.\n\nKit includes:\n\nx1 Canon C300 III body\nx 1 Canon Professional OLED Electronic Viewfinder EVF-V704\nx1 Canon Handgrip trigger\n\nx 1 Fx lion v-mount plate\nx 2 Canon BP-A60\nx 1 Canon BP- A30\n\nx 1 Sandisk CFExpress 515GB\nx 1 Angelbird CFexpress SE Type B Card - 512GB\nx 1 CFExpress card reader",
		price: 140,
		priceExclVat: 140,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "QRUTn8VgW_HquXBwh4dHPw",
		image: "https://images.wedio.com/images/listing_images/images/1973182/medium/canon-c300-mark-iii-body-only--29045485.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709300-canon-eos-c300-mk-iii",
		categories: ["1", "2"],
		productionType: "global-production-type-video",
		brand: "canon",
		items: ["Canon EOS C300 MK III"],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "QRUTn8VgW_HquXBwh4dHPw",
			name: "Marco Beyermann Plaza",
			username: "beyermann10",
			image: "https://images.wedio.com/images/people/images/QRUTn8VgW_HquXBwh4dHPw/thumb/About-me_Portrait-2.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 1,
			percentagePositive: 100,
			isPrime: false,
			feedback: 5,
		},
		objectID: "709300",
		_highlightResult: {
			title: {
				value: "Canon EOS C300 MK III",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS C300 MK III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "beyermann10",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon R6 Mark II + RF 24-70mm",
		description:
			"Dear Fellow Creators  \n\nPLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT \n\nCollection Locations: Paddington, Holborn, Camden, Liverpool Street, Southwark, Shoreditch, Ilford or Grays.  \n\n Collection & Return Hours: 08:00 - 20:00 Mon-Sun  -\n\nDelivery Options Available\n\n Delivery £20 or Delivery and collection £30\n ☎️ WhatsApp 07506380737   \n\n Bundle Includes: \n▪️Canon EOS R6 Mark II \n▪️Canon RF 24-70mm Lens  \n▪️2x Canon batteries  \n▪️Charger \n ▪️x2 64GB Sandisk Cards\n ▪️Carry backpack  \n\n BOOK FOR A WEEK, ONLY PAY 4 DAYS.  \n\nBOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n ☑️ Add any lens below for £15/day (or £75/week)  \n\nRF 28-70mm f/2 L USM \nRF 24-70mm F2.8 \nRF 85mm F1.2  \nRF 35mm F1.4 \nRF 15-35mm F2.8 \nEF 70-200 mm f/2.8 L USM \nEF 50 mm-f/1.4 USM  \nEF-S 15-85mm f/3.5-5.6 IS USM \nEF-S 18-55mm f/3.5-5.6 IS \nEF 75-300mm F4.0-5.6 III  \nSigma 150-500mm f5-6.3 \nEF-EOS R Mount Adapter Variable ND Filter \nA Godox AD200 Pro \nGodox Xpro C Flash Trigger  \nGodox V860II-C Speedlite \nTripod \nDeity V-Mic D3 Pro \n\n We pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\n  ID Required \n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1973146/medium/1921553F-0312-4856-B48C-668494C97713.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709291-canon-r6-mark-ii-rf-24-70mm",
		categories: ["1", "4"],
		items: [
			"Canon R6 mark II + RF 24-70mm F2.8",
			"Canon R6 Mark II",
			"Canon RF 24-70mm F2.8",
		],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "709291",
		_highlightResult: {
			title: {
				value: "Canon R6 Mark II + RF 24-70mm",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon R6 mark II + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon R6 Mark II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
		description:
			"Please ask for availability before booking.\n\nWhat's Included:\n\n- 1 * Canon Canon EOS R6 II Body\n- 2 * LP-E6NH Batteries\n- 1 * Battery Charger\n- 1 * Canon Camera Sling Strap\n- 2 * Lexar 256GB UHS-II Memory Cards\n- 1 * Camera Backpack",
		price: 29,
		priceExclVat: 24.166656,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "Mxvv6lya9KY_hxKLwu7vtg",
		image: "https://images.wedio.com/images/listing_images/images/1971255/medium/1.-Body-Only.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: true,
		offerShipping: true,
		offerFreeShipping: false,
		offerPickup: true,
		offerBuyNow: false,
		offerMakeOffer: true,
		gearCondition: "good",
		url: "https://www.wedio.com/listings/708430-canon-eos-r6-ii-body-only-2-batteries-2-256gb-uhs-ii-sd-cards",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: [
			" Canon EOS R6 II",
			"LP-E6NH",
			"Lexar 256GB UHS-II SD Card",
			"Canon EOS R6",
		],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "Mxvv6lya9KY_hxKLwu7vtg",
			name: "GeekyGain",
			username: "geekygain",
			image: "https://images.wedio.com/images/people/images/Mxvv6lya9KY_hxKLwu7vtg/thumb/GG-Logo-Black-(TM).png",
			country: "GB",
			vatVerified: true,
			reviews: 3,
			isPrime: false,
			feedback: 5,
		},
		objectID: "708430",
		_highlightResult: {
			title: {
				value: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: " Canon EOS R6 II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LP-E6NH",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Lexar 256GB UHS-II SD Card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R6",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "geekygain",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Sony A7III + Tamron 28-75mm f2.8",
		description:
			"Package includes:\n\n1x Sony A7III\n1x Tamron 28-75mm f2.8\n4x Batteries\n2x Memory cards 64GB\n\n\n\n\nMy full kit list:   \n\n- Sony A7 III  \n- Canon 80D  \n- Samyang AF 85mm F1.4 FE\n- Sigma AF 105mm f2.8\n- Tamron 28-75mm f2.8  \n- Canon EF 50mm f1.8 STM  \n- Røde VideoMic Pro \n- Røde Wireless Go + Lav Mic  \n- Zhiyun Crane Plus  \n- DJI Osmo Mobile 2  \n- Sennheiser MKE 400  \n- Hollyland Lark C1 Wireless \n",
		price: 349,
		priceExclVat: 349,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "sbCL-ROfluclifrqKt2PXg",
		image: "https://images.wedio.com/images/listing_images/images/1970260/medium/sonya7iii.jpg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/708022-sony-a7iii-tamron-28-75mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "sony",
		items: ["Sony Alpha A7 III"],
		_geoloc: [
			{
				lat: 56.146,
				lng: 10.2027,
			},
			{
				lat: 56.1895,
				lng: 10.1327,
			},
		],
		city: "Aarhus",
		author: {
			id: "sbCL-ROfluclifrqKt2PXg",
			name: "monikabara",
			username: "monikabar",
			image: "https://images.wedio.com/images/people/images/sbCL-ROfluclifrqKt2PXg/thumb/Facetune_21-08-2023-12-02-09.jpeg",
			country: "DK",
			vatVerified: false,
			reviews: 23,
			isPrime: true,
			feedback: 5,
		},
		objectID: "708022",
		_highlightResult: {
			title: {
				value: "Sony A7III + Tamron 28-75mm f2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "monikabar",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R5 + RF 24-70mm F2.8",
		description:
			" Dear Fellow Creators \n- PLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT ?\n\n- Collection Locations: Paddington, Holborn, Camden, Southwark, Shoreditch, Ilford or Grays. \n- Collection & Return Hours: 08:00 - 20:00 Mon-Sun \n- Delivery Options Available ? Delivery £10 or Delivery and collection £15\n☎️ WhatsApp 07506380737\n\n\n- Bundle Includes:\n▪️Canon EOS R5\n▪️Canon RF 24-70mm Lens \n▪️2x Canon batteries \n▪️Charger\n▪️x1 CF Express Card 256GB\n▪️x2 64GB Sandisk Cards\n▪️Carry backpack\n\n- BOOK FOR A WEEK, ONLY PAY 4 DAYS. \n- BOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n☑️ Add any lens below for £15/day (or £75/week)\n\nRF 28-70mm f/2 L USM\nRF 24-70mm F2.8\nRF 85mm F1.2 \nRF 35mm F1.4\nRF 15-35mm F2.8\nEF 70-200 mm f/2.8 L USM\nEF 50 mm-f/1.4 USM \nEF-S 15-85mm f/3.5-5.6 IS USM\nEF-S 18-55mm f/3.5-5.6 IS\nEF 75-300mm F4.0-5.6 III \nSigma 150-500mm f5-6.3\nEF-EOS R Mount Adapter Variable ND Filter A\nGodox AD200 Pro\nGodox Xpro C Flash Trigger \nGodox V860II-C Speedlite\nTripod\nDeity V-Mic D3 Pro\n\nWe pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\nID Required\n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1961284/medium/791DBBCB-6C8D-4A09-B899-CDBA331454D2.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/704468-canon-eos-r5-rf-24-70mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: ["Canon EOS R5 + RF 24-70mm F2.8", "Canon EOS R5", "RF 24-70mm F2.8"],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "704468",
		_highlightResult: {
			title: {
				value: "Canon EOS R5 + RF 24-70mm F2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS R5 + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R5",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
		description:
			'1x Sony Alpha A7 IV\n1x Sony FE 24-105mm f/4 G OSS Lens\n1x SONY ECM-M1 SHOTGUN MICROPHONE\n1x MANFROTTO MK190 XPRO3 W. BALL HEAD\n1x NANLITE FS-150 LED DAYLIGHT SPOT LIGHT\n1x GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT\n1x KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER\n2x SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII\n1x LEXAR SD 128GB U3 V90 UHS-II R300/W260\n',
		price: 2000,
		priceExclVat: 1600,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "Jz8oFYqR9Pf-8ekzK08jvQ",
		image: "https://images.wedio.com/images/listing_images/images/1984171/medium/aegte-3.jpg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714256-video-pack-sony-a7-iv-24-108-lens-sound-lighting",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"youtube",
			"live_streaming",
			"portraits",
			"safari",
			"landscape",
			"birding",
			"food",
			"product",
			"night",
			"interviews",
			"documentary",
			"action",
			"archaeology",
			"real_estate",
			"concert",
			"journalism",
			"music_videos",
			"instagram",
			"vlogging",
			"wildlife",
			"slow_motion_video",
			"tattoo",
			"selfies",
			"large_group",
			"indoors",
			"outside",
			"high_speed_video",
			"podcast",
			"timelapse",
			"other",
		],
		productionType: "global-production-type-still-and-video",
		type: ["wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony Alpha A7 IV",
			"Sony FE 24-105mm f/4 G OSS Lens",
			"SONY ECM-M1 SHOTGUN MICROPHONE",
			"MANFROTTO MK190 XPRO3 W. BALL HEAD",
			"NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
			"GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
			'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
			"SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
			"LEXAR SD 128GB U3 V90 UHS-II R300/W260",
			"LaCie USB-C 4 TB Harddisk",
		],
		_geoloc: [
			{
				lat: 55.6924,
				lng: 12.5543,
			},
		],
		city: "Copenhagen",
		author: {
			id: "Jz8oFYqR9Pf-8ekzK08jvQ",
			name: "aegte",
			username: "aegte",
			image: "https://images.wedio.com/images/people/images/Jz8oFYqR9Pf-8ekzK08jvQ/thumb/INSTA---aegte-front-(2).png",
			country: "DK",
			vatVerified: true,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714256",
		_highlightResult: {
			title: {
				value: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 IV",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-105mm f/4 G OSS Lens",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY ECM-M1 SHOTGUN MICROPHONE",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "MANFROTTO MK190 XPRO3 W. BALL HEAD",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: 'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR SD 128GB U3 V90 UHS-II R300/W260",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LaCie USB-C 4 TB Harddisk",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "aegte",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Bell & Howell Autoload Super 8 Camera",
		description:
			"What's Included:\n\n- Bell & Howell Autoload Super 8 Camera\n- 4x AAA Batteries",
		price: 10,
		priceExclVat: 10,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "6q2q8PvHMe9GH2SdVdISfQ",
		image: "https://images.wedio.com/images/listing_images/images/1984084/medium/WhatsApp-Image-2024-02-09-at-5.05.44-pm-2.jpeg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714199-bell-howell-autoload-super-8-camera",
		categories: ["1", "9"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"documentary",
			"concert",
			"music_videos",
			"indoors",
			"outside",
			"other",
		],
		productionType: "global-production-type-video",
		brand: "other_brand",
		items: ["Bell & Howell Autoload Super 8 Camera"],
		_geoloc: {
			lat: 53.4891,
			lng: -2.27418,
		},
		author: {
			id: "6q2q8PvHMe9GH2SdVdISfQ",
			name: "Will Carswell",
			username: "williamc1",
			image: "https://images.wedio.com/images/people/images/6q2q8PvHMe9GH2SdVdISfQ/thumb/Profile-picture.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714199",
		_highlightResult: {
			title: {
				value: "Bell & Howell Autoload Super 8 Camera",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Bell & Howell Autoload Super 8 Camera",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "williamc1",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
		description:
			"Sony's flagship high-resolution-kamera med 61mp og 10-bit video-specs.\n\nAnmeldelse:\nhttps://www.youtube.com/watch?v=TqZk1zW2i1U\n\nSkriv for spørgsmål!\n\n5x Sony NP-FZ100 battery\n1x Sony A7R V\n1x LEXAR CFExpress 160GB-memory card\n1x Sony FE 24-70mm f2.8 G Master\n1x Sony FE 35mm f2.8 G Master\n1x Sony FE 20mm F1.8 G\n",
		price: 1000,
		priceExclVat: 800,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "rswuYE-4Pp5dCmv-J65dtw",
		image: "https://images.wedio.com/images/listing_images/images/1982657/medium/PSHOT-SONY-A7R-V-TOP-640PX.JPG",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/713796-sony-a7r-v-megapixel-beast-til-stills-og-8k-video-med-tre-objektiver",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"portraits",
			"astrophotography",
			"landscape",
			"birding",
			"food",
			"product",
			"documentary",
			"journalism",
			"instagram",
			"vlogging",
			"indoors",
			"outside",
		],
		productionType: "global-production-type-still-and-video",
		type: ["normal", "auto", "wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony NP-FZ100 battery",
			"Sony A7R V",
			"LEXAR CFExpress 160GB-memory card",
			"Sony FE 24-70mm f2.8 G Master",
			"Sony FE 35mm f2.8 G Master",
			"Sony FE 20mm F1.8 G",
		],
		_geoloc: {
			lat: 55.6761,
			lng: 12.5683,
		},
		city: "Copenhagen",
		author: {
			id: "rswuYE-4Pp5dCmv-J65dtw",
			name: "gemmergemmer",
			username: "gemmergemmer",
			image: "https://images.wedio.com/images/people/images/rswuYE-4Pp5dCmv-J65dtw/thumb/_DSC7301.jpg",
			country: "DK",
			vatVerified: true,
			reviews: 74,
			isPrime: false,
			feedback: 5,
		},
		objectID: "713796",
		_highlightResult: {
			title: {
				value: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony NP-FZ100 battery",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony A7R V",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR CFExpress 160GB-memory card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-70mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 35mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 20mm F1.8 G",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "gemmergemmer",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS C300 MK III",
		description:
			"Canon C300 III body only. THE KIT DOES NOT ICLUDE LENS.\n\nPlease feel free to contact for a customise package or see other listing.\n\nKit includes:\n\nx1 Canon C300 III body\nx 1 Canon Professional OLED Electronic Viewfinder EVF-V704\nx1 Canon Handgrip trigger\n\nx 1 Fx lion v-mount plate\nx 2 Canon BP-A60\nx 1 Canon BP- A30\n\nx 1 Sandisk CFExpress 515GB\nx 1 Angelbird CFexpress SE Type B Card - 512GB\nx 1 CFExpress card reader",
		price: 140,
		priceExclVat: 140,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "QRUTn8VgW_HquXBwh4dHPw",
		image: "https://images.wedio.com/images/listing_images/images/1973182/medium/canon-c300-mark-iii-body-only--29045485.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709300-canon-eos-c300-mk-iii",
		categories: ["1", "2"],
		productionType: "global-production-type-video",
		brand: "canon",
		items: ["Canon EOS C300 MK III"],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "QRUTn8VgW_HquXBwh4dHPw",
			name: "Marco Beyermann Plaza",
			username: "beyermann10",
			image: "https://images.wedio.com/images/people/images/QRUTn8VgW_HquXBwh4dHPw/thumb/About-me_Portrait-2.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 1,
			percentagePositive: 100,
			isPrime: false,
			feedback: 5,
		},
		objectID: "709300",
		_highlightResult: {
			title: {
				value: "Canon EOS C300 MK III",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS C300 MK III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "beyermann10",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon R6 Mark II + RF 24-70mm",
		description:
			"Dear Fellow Creators  \n\nPLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT \n\nCollection Locations: Paddington, Holborn, Camden, Liverpool Street, Southwark, Shoreditch, Ilford or Grays.  \n\n Collection & Return Hours: 08:00 - 20:00 Mon-Sun  -\n\nDelivery Options Available\n\n Delivery £20 or Delivery and collection £30\n ☎️ WhatsApp 07506380737   \n\n Bundle Includes: \n▪️Canon EOS R6 Mark II \n▪️Canon RF 24-70mm Lens  \n▪️2x Canon batteries  \n▪️Charger \n ▪️x2 64GB Sandisk Cards\n ▪️Carry backpack  \n\n BOOK FOR A WEEK, ONLY PAY 4 DAYS.  \n\nBOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n ☑️ Add any lens below for £15/day (or £75/week)  \n\nRF 28-70mm f/2 L USM \nRF 24-70mm F2.8 \nRF 85mm F1.2  \nRF 35mm F1.4 \nRF 15-35mm F2.8 \nEF 70-200 mm f/2.8 L USM \nEF 50 mm-f/1.4 USM  \nEF-S 15-85mm f/3.5-5.6 IS USM \nEF-S 18-55mm f/3.5-5.6 IS \nEF 75-300mm F4.0-5.6 III  \nSigma 150-500mm f5-6.3 \nEF-EOS R Mount Adapter Variable ND Filter \nA Godox AD200 Pro \nGodox Xpro C Flash Trigger  \nGodox V860II-C Speedlite \nTripod \nDeity V-Mic D3 Pro \n\n We pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\n  ID Required \n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1973146/medium/1921553F-0312-4856-B48C-668494C97713.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709291-canon-r6-mark-ii-rf-24-70mm",
		categories: ["1", "4"],
		items: [
			"Canon R6 mark II + RF 24-70mm F2.8",
			"Canon R6 Mark II",
			"Canon RF 24-70mm F2.8",
		],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "709291",
		_highlightResult: {
			title: {
				value: "Canon R6 Mark II + RF 24-70mm",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon R6 mark II + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon R6 Mark II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
		description:
			"Please ask for availability before booking.\n\nWhat's Included:\n\n- 1 * Canon Canon EOS R6 II Body\n- 2 * LP-E6NH Batteries\n- 1 * Battery Charger\n- 1 * Canon Camera Sling Strap\n- 2 * Lexar 256GB UHS-II Memory Cards\n- 1 * Camera Backpack",
		price: 29,
		priceExclVat: 24.166656,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "Mxvv6lya9KY_hxKLwu7vtg",
		image: "https://images.wedio.com/images/listing_images/images/1971255/medium/1.-Body-Only.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: true,
		offerShipping: true,
		offerFreeShipping: false,
		offerPickup: true,
		offerBuyNow: false,
		offerMakeOffer: true,
		gearCondition: "good",
		url: "https://www.wedio.com/listings/708430-canon-eos-r6-ii-body-only-2-batteries-2-256gb-uhs-ii-sd-cards",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: [
			" Canon EOS R6 II",
			"LP-E6NH",
			"Lexar 256GB UHS-II SD Card",
			"Canon EOS R6",
		],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "Mxvv6lya9KY_hxKLwu7vtg",
			name: "GeekyGain",
			username: "geekygain",
			image: "https://images.wedio.com/images/people/images/Mxvv6lya9KY_hxKLwu7vtg/thumb/GG-Logo-Black-(TM).png",
			country: "GB",
			vatVerified: true,
			reviews: 3,
			isPrime: false,
			feedback: 5,
		},
		objectID: "708430",
		_highlightResult: {
			title: {
				value: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: " Canon EOS R6 II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LP-E6NH",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Lexar 256GB UHS-II SD Card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R6",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "geekygain",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Sony A7III + Tamron 28-75mm f2.8",
		description:
			"Package includes:\n\n1x Sony A7III\n1x Tamron 28-75mm f2.8\n4x Batteries\n2x Memory cards 64GB\n\n\n\n\nMy full kit list:   \n\n- Sony A7 III  \n- Canon 80D  \n- Samyang AF 85mm F1.4 FE\n- Sigma AF 105mm f2.8\n- Tamron 28-75mm f2.8  \n- Canon EF 50mm f1.8 STM  \n- Røde VideoMic Pro \n- Røde Wireless Go + Lav Mic  \n- Zhiyun Crane Plus  \n- DJI Osmo Mobile 2  \n- Sennheiser MKE 400  \n- Hollyland Lark C1 Wireless \n",
		price: 349,
		priceExclVat: 349,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "sbCL-ROfluclifrqKt2PXg",
		image: "https://images.wedio.com/images/listing_images/images/1970260/medium/sonya7iii.jpg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/708022-sony-a7iii-tamron-28-75mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "sony",
		items: ["Sony Alpha A7 III"],
		_geoloc: [
			{
				lat: 56.146,
				lng: 10.2027,
			},
			{
				lat: 56.1895,
				lng: 10.1327,
			},
		],
		city: "Aarhus",
		author: {
			id: "sbCL-ROfluclifrqKt2PXg",
			name: "monikabara",
			username: "monikabar",
			image: "https://images.wedio.com/images/people/images/sbCL-ROfluclifrqKt2PXg/thumb/Facetune_21-08-2023-12-02-09.jpeg",
			country: "DK",
			vatVerified: false,
			reviews: 23,
			isPrime: true,
			feedback: 5,
		},
		objectID: "708022",
		_highlightResult: {
			title: {
				value: "Sony A7III + Tamron 28-75mm f2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "monikabar",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R5 + RF 24-70mm F2.8",
		description:
			" Dear Fellow Creators \n- PLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT ?\n\n- Collection Locations: Paddington, Holborn, Camden, Southwark, Shoreditch, Ilford or Grays. \n- Collection & Return Hours: 08:00 - 20:00 Mon-Sun \n- Delivery Options Available ? Delivery £10 or Delivery and collection £15\n☎️ WhatsApp 07506380737\n\n\n- Bundle Includes:\n▪️Canon EOS R5\n▪️Canon RF 24-70mm Lens \n▪️2x Canon batteries \n▪️Charger\n▪️x1 CF Express Card 256GB\n▪️x2 64GB Sandisk Cards\n▪️Carry backpack\n\n- BOOK FOR A WEEK, ONLY PAY 4 DAYS. \n- BOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n☑️ Add any lens below for £15/day (or £75/week)\n\nRF 28-70mm f/2 L USM\nRF 24-70mm F2.8\nRF 85mm F1.2 \nRF 35mm F1.4\nRF 15-35mm F2.8\nEF 70-200 mm f/2.8 L USM\nEF 50 mm-f/1.4 USM \nEF-S 15-85mm f/3.5-5.6 IS USM\nEF-S 18-55mm f/3.5-5.6 IS\nEF 75-300mm F4.0-5.6 III \nSigma 150-500mm f5-6.3\nEF-EOS R Mount Adapter Variable ND Filter A\nGodox AD200 Pro\nGodox Xpro C Flash Trigger \nGodox V860II-C Speedlite\nTripod\nDeity V-Mic D3 Pro\n\nWe pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\nID Required\n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1961284/medium/791DBBCB-6C8D-4A09-B899-CDBA331454D2.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/704468-canon-eos-r5-rf-24-70mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: ["Canon EOS R5 + RF 24-70mm F2.8", "Canon EOS R5", "RF 24-70mm F2.8"],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "704468",
		_highlightResult: {
			title: {
				value: "Canon EOS R5 + RF 24-70mm F2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS R5 + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R5",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
		description:
			'1x Sony Alpha A7 IV\n1x Sony FE 24-105mm f/4 G OSS Lens\n1x SONY ECM-M1 SHOTGUN MICROPHONE\n1x MANFROTTO MK190 XPRO3 W. BALL HEAD\n1x NANLITE FS-150 LED DAYLIGHT SPOT LIGHT\n1x GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT\n1x KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER\n2x SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII\n1x LEXAR SD 128GB U3 V90 UHS-II R300/W260\n',
		price: 2000,
		priceExclVat: 1600,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "Jz8oFYqR9Pf-8ekzK08jvQ",
		image: "https://images.wedio.com/images/listing_images/images/1984171/medium/aegte-3.jpg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714256-video-pack-sony-a7-iv-24-108-lens-sound-lighting",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"youtube",
			"live_streaming",
			"portraits",
			"safari",
			"landscape",
			"birding",
			"food",
			"product",
			"night",
			"interviews",
			"documentary",
			"action",
			"archaeology",
			"real_estate",
			"concert",
			"journalism",
			"music_videos",
			"instagram",
			"vlogging",
			"wildlife",
			"slow_motion_video",
			"tattoo",
			"selfies",
			"large_group",
			"indoors",
			"outside",
			"high_speed_video",
			"podcast",
			"timelapse",
			"other",
		],
		productionType: "global-production-type-still-and-video",
		type: ["wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony Alpha A7 IV",
			"Sony FE 24-105mm f/4 G OSS Lens",
			"SONY ECM-M1 SHOTGUN MICROPHONE",
			"MANFROTTO MK190 XPRO3 W. BALL HEAD",
			"NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
			"GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
			'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
			"SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
			"LEXAR SD 128GB U3 V90 UHS-II R300/W260",
			"LaCie USB-C 4 TB Harddisk",
		],
		_geoloc: [
			{
				lat: 55.6924,
				lng: 12.5543,
			},
		],
		city: "Copenhagen",
		author: {
			id: "Jz8oFYqR9Pf-8ekzK08jvQ",
			name: "aegte",
			username: "aegte",
			image: "https://images.wedio.com/images/people/images/Jz8oFYqR9Pf-8ekzK08jvQ/thumb/INSTA---aegte-front-(2).png",
			country: "DK",
			vatVerified: true,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714256",
		_highlightResult: {
			title: {
				value: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 IV",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-105mm f/4 G OSS Lens",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY ECM-M1 SHOTGUN MICROPHONE",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "MANFROTTO MK190 XPRO3 W. BALL HEAD",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: 'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR SD 128GB U3 V90 UHS-II R300/W260",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LaCie USB-C 4 TB Harddisk",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "aegte",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Bell & Howell Autoload Super 8 Camera",
		description:
			"What's Included:\n\n- Bell & Howell Autoload Super 8 Camera\n- 4x AAA Batteries",
		price: 10,
		priceExclVat: 10,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "6q2q8PvHMe9GH2SdVdISfQ",
		image: "https://images.wedio.com/images/listing_images/images/1984084/medium/WhatsApp-Image-2024-02-09-at-5.05.44-pm-2.jpeg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714199-bell-howell-autoload-super-8-camera",
		categories: ["1", "9"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"documentary",
			"concert",
			"music_videos",
			"indoors",
			"outside",
			"other",
		],
		productionType: "global-production-type-video",
		brand: "other_brand",
		items: ["Bell & Howell Autoload Super 8 Camera"],
		_geoloc: {
			lat: 53.4891,
			lng: -2.27418,
		},
		author: {
			id: "6q2q8PvHMe9GH2SdVdISfQ",
			name: "Will Carswell",
			username: "williamc1",
			image: "https://images.wedio.com/images/people/images/6q2q8PvHMe9GH2SdVdISfQ/thumb/Profile-picture.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714199",
		_highlightResult: {
			title: {
				value: "Bell & Howell Autoload Super 8 Camera",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Bell & Howell Autoload Super 8 Camera",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "williamc1",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
		description:
			"Sony's flagship high-resolution-kamera med 61mp og 10-bit video-specs.\n\nAnmeldelse:\nhttps://www.youtube.com/watch?v=TqZk1zW2i1U\n\nSkriv for spørgsmål!\n\n5x Sony NP-FZ100 battery\n1x Sony A7R V\n1x LEXAR CFExpress 160GB-memory card\n1x Sony FE 24-70mm f2.8 G Master\n1x Sony FE 35mm f2.8 G Master\n1x Sony FE 20mm F1.8 G\n",
		price: 1000,
		priceExclVat: 800,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "rswuYE-4Pp5dCmv-J65dtw",
		image: "https://images.wedio.com/images/listing_images/images/1982657/medium/PSHOT-SONY-A7R-V-TOP-640PX.JPG",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/713796-sony-a7r-v-megapixel-beast-til-stills-og-8k-video-med-tre-objektiver",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"portraits",
			"astrophotography",
			"landscape",
			"birding",
			"food",
			"product",
			"documentary",
			"journalism",
			"instagram",
			"vlogging",
			"indoors",
			"outside",
		],
		productionType: "global-production-type-still-and-video",
		type: ["normal", "auto", "wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony NP-FZ100 battery",
			"Sony A7R V",
			"LEXAR CFExpress 160GB-memory card",
			"Sony FE 24-70mm f2.8 G Master",
			"Sony FE 35mm f2.8 G Master",
			"Sony FE 20mm F1.8 G",
		],
		_geoloc: {
			lat: 55.6761,
			lng: 12.5683,
		},
		city: "Copenhagen",
		author: {
			id: "rswuYE-4Pp5dCmv-J65dtw",
			name: "gemmergemmer",
			username: "gemmergemmer",
			image: "https://images.wedio.com/images/people/images/rswuYE-4Pp5dCmv-J65dtw/thumb/_DSC7301.jpg",
			country: "DK",
			vatVerified: true,
			reviews: 74,
			isPrime: false,
			feedback: 5,
		},
		objectID: "713796",
		_highlightResult: {
			title: {
				value: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony NP-FZ100 battery",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony A7R V",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR CFExpress 160GB-memory card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-70mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 35mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 20mm F1.8 G",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "gemmergemmer",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Cannon C500 II 5.9 K, FULL FRAME KIT",
		description:
			"1x Cannon C500 II EF mount\n1x Otus Zeiss 3 camera lens bundle\n4x Batteries Dynacore + charger\n5x Anglebird Match Pack 512 GB  \nTilta Camera Cage for Cannon V Mount\nPL MOUNT ON DEMAND (with ULTRA PRIME objectives quality of the picture similar to ARRI cameras)\n1x Saramonic set wireless microphone\n1x Sehnheiser MKH 418 P48 Microphone\n2x  LED RAYZER MC 100 PANELS with adjustable temperatures and colours\n\nAll equipment in PELICAN and HCRP cases\n1x MANFROTTO camera stand \n\n\n\n",
		price: 400,
		priceExclVat: 400,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "EUR",
		authorId: "4b2r31AaS0PZ6IrZGFFqjA",
		image: "https://images.wedio.com/images/listing_images/images/1973330/medium/01.jpg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709375-cannon-c500-ii-5-9-k-full-frame-kit",
		categories: ["1", "2"],
		productionType: "global-production-type-still-and-video",
		items: [
			"Cannon C500 II",
			"Otus Zeiss 3 camera lens bundle",
			"Angelbird Match Pack for Canon EOS 500 512 GB ",
			"BATTERIES DYNACORE 4 PIECES + CHARGER",
			"TILTA CAMERA CAGE FOR CANNON V MOUNT",
			"SARAMONIC SET WIRELESS MICROPHONES",
			"SEHNHEISER MKH 418 P48 MICROPHONE ",
			"PL MOUNT ON DEMAND",
		],
		_geoloc: {
			lat: 52.45355,
			lng: 13.315171,
		},
		city: "Berlin",
		author: {
			id: "4b2r31AaS0PZ6IrZGFFqjA",
			name: "armanini",
			username: "armanini",
			image: "https://images.wedio.com/images/people/images/4b2r31AaS0PZ6IrZGFFqjA/thumb/data",
			country: "HR",
			vatVerified: false,
			reviews: 0,
			percentagePositive: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "709375",
		_highlightResult: {
			title: {
				value: "Cannon C500 II 5.9 K, FULL FRAME KIT",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Cannon C500 II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Otus Zeiss 3 camera lens bundle",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Angelbird Match Pack for Canon EOS 500 512 GB ",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "BATTERIES DYNACORE 4 PIECES + CHARGER",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "TILTA CAMERA CAGE FOR CANNON V MOUNT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SARAMONIC SET WIRELESS MICROPHONES",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SEHNHEISER MKH 418 P48 MICROPHONE ",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "PL MOUNT ON DEMAND",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "armanini",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS C300 MK III",
		description:
			"Canon C300 III body only. THE KIT DOES NOT ICLUDE LENS.\n\nPlease feel free to contact for a customise package or see other listing.\n\nKit includes:\n\nx1 Canon C300 III body\nx 1 Canon Professional OLED Electronic Viewfinder EVF-V704\nx1 Canon Handgrip trigger\n\nx 1 Fx lion v-mount plate\nx 2 Canon BP-A60\nx 1 Canon BP- A30\n\nx 1 Sandisk CFExpress 515GB\nx 1 Angelbird CFexpress SE Type B Card - 512GB\nx 1 CFExpress card reader",
		price: 140,
		priceExclVat: 140,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "QRUTn8VgW_HquXBwh4dHPw",
		image: "https://images.wedio.com/images/listing_images/images/1973182/medium/canon-c300-mark-iii-body-only--29045485.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709300-canon-eos-c300-mk-iii",
		categories: ["1", "2"],
		productionType: "global-production-type-video",
		brand: "canon",
		items: ["Canon EOS C300 MK III"],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "QRUTn8VgW_HquXBwh4dHPw",
			name: "Marco Beyermann Plaza",
			username: "beyermann10",
			image: "https://images.wedio.com/images/people/images/QRUTn8VgW_HquXBwh4dHPw/thumb/About-me_Portrait-2.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 1,
			percentagePositive: 100,
			isPrime: false,
			feedback: 5,
		},
		objectID: "709300",
		_highlightResult: {
			title: {
				value: "Canon EOS C300 MK III",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS C300 MK III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "beyermann10",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon R6 Mark II + RF 24-70mm",
		description:
			"Dear Fellow Creators  \n\nPLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT \n\nCollection Locations: Paddington, Holborn, Camden, Liverpool Street, Southwark, Shoreditch, Ilford or Grays.  \n\n Collection & Return Hours: 08:00 - 20:00 Mon-Sun  -\n\nDelivery Options Available\n\n Delivery £20 or Delivery and collection £30\n ☎️ WhatsApp 07506380737   \n\n Bundle Includes: \n▪️Canon EOS R6 Mark II \n▪️Canon RF 24-70mm Lens  \n▪️2x Canon batteries  \n▪️Charger \n ▪️x2 64GB Sandisk Cards\n ▪️Carry backpack  \n\n BOOK FOR A WEEK, ONLY PAY 4 DAYS.  \n\nBOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n ☑️ Add any lens below for £15/day (or £75/week)  \n\nRF 28-70mm f/2 L USM \nRF 24-70mm F2.8 \nRF 85mm F1.2  \nRF 35mm F1.4 \nRF 15-35mm F2.8 \nEF 70-200 mm f/2.8 L USM \nEF 50 mm-f/1.4 USM  \nEF-S 15-85mm f/3.5-5.6 IS USM \nEF-S 18-55mm f/3.5-5.6 IS \nEF 75-300mm F4.0-5.6 III  \nSigma 150-500mm f5-6.3 \nEF-EOS R Mount Adapter Variable ND Filter \nA Godox AD200 Pro \nGodox Xpro C Flash Trigger  \nGodox V860II-C Speedlite \nTripod \nDeity V-Mic D3 Pro \n\n We pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\n  ID Required \n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1973146/medium/1921553F-0312-4856-B48C-668494C97713.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709291-canon-r6-mark-ii-rf-24-70mm",
		categories: ["1", "4"],
		items: [
			"Canon R6 mark II + RF 24-70mm F2.8",
			"Canon R6 Mark II",
			"Canon RF 24-70mm F2.8",
		],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "709291",
		_highlightResult: {
			title: {
				value: "Canon R6 Mark II + RF 24-70mm",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon R6 mark II + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon R6 Mark II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
		description:
			"Please ask for availability before booking.\n\nWhat's Included:\n\n- 1 * Canon Canon EOS R6 II Body\n- 2 * LP-E6NH Batteries\n- 1 * Battery Charger\n- 1 * Canon Camera Sling Strap\n- 2 * Lexar 256GB UHS-II Memory Cards\n- 1 * Camera Backpack",
		price: 29,
		priceExclVat: 24.166656,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "Mxvv6lya9KY_hxKLwu7vtg",
		image: "https://images.wedio.com/images/listing_images/images/1971255/medium/1.-Body-Only.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: true,
		offerShipping: true,
		offerFreeShipping: false,
		offerPickup: true,
		offerBuyNow: false,
		offerMakeOffer: true,
		gearCondition: "good",
		url: "https://www.wedio.com/listings/708430-canon-eos-r6-ii-body-only-2-batteries-2-256gb-uhs-ii-sd-cards",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: [
			" Canon EOS R6 II",
			"LP-E6NH",
			"Lexar 256GB UHS-II SD Card",
			"Canon EOS R6",
		],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "Mxvv6lya9KY_hxKLwu7vtg",
			name: "GeekyGain",
			username: "geekygain",
			image: "https://images.wedio.com/images/people/images/Mxvv6lya9KY_hxKLwu7vtg/thumb/GG-Logo-Black-(TM).png",
			country: "GB",
			vatVerified: true,
			reviews: 3,
			isPrime: false,
			feedback: 5,
		},
		objectID: "708430",
		_highlightResult: {
			title: {
				value: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: " Canon EOS R6 II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LP-E6NH",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Lexar 256GB UHS-II SD Card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R6",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "geekygain",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Sony A7III + Tamron 28-75mm f2.8",
		description:
			"Package includes:\n\n1x Sony A7III\n1x Tamron 28-75mm f2.8\n4x Batteries\n2x Memory cards 64GB\n\n\n\n\nMy full kit list:   \n\n- Sony A7 III  \n- Canon 80D  \n- Samyang AF 85mm F1.4 FE\n- Sigma AF 105mm f2.8\n- Tamron 28-75mm f2.8  \n- Canon EF 50mm f1.8 STM  \n- Røde VideoMic Pro \n- Røde Wireless Go + Lav Mic  \n- Zhiyun Crane Plus  \n- DJI Osmo Mobile 2  \n- Sennheiser MKE 400  \n- Hollyland Lark C1 Wireless \n",
		price: 349,
		priceExclVat: 349,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "sbCL-ROfluclifrqKt2PXg",
		image: "https://images.wedio.com/images/listing_images/images/1970260/medium/sonya7iii.jpg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/708022-sony-a7iii-tamron-28-75mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "sony",
		items: ["Sony Alpha A7 III"],
		_geoloc: [
			{
				lat: 56.146,
				lng: 10.2027,
			},
			{
				lat: 56.1895,
				lng: 10.1327,
			},
		],
		city: "Aarhus",
		author: {
			id: "sbCL-ROfluclifrqKt2PXg",
			name: "monikabara",
			username: "monikabar",
			image: "https://images.wedio.com/images/people/images/sbCL-ROfluclifrqKt2PXg/thumb/Facetune_21-08-2023-12-02-09.jpeg",
			country: "DK",
			vatVerified: false,
			reviews: 23,
			isPrime: true,
			feedback: 5,
		},
		objectID: "708022",
		_highlightResult: {
			title: {
				value: "Sony A7III + Tamron 28-75mm f2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "monikabar",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R5 + RF 24-70mm F2.8",
		description:
			" Dear Fellow Creators \n- PLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT ?\n\n- Collection Locations: Paddington, Holborn, Camden, Southwark, Shoreditch, Ilford or Grays. \n- Collection & Return Hours: 08:00 - 20:00 Mon-Sun \n- Delivery Options Available ? Delivery £10 or Delivery and collection £15\n☎️ WhatsApp 07506380737\n\n\n- Bundle Includes:\n▪️Canon EOS R5\n▪️Canon RF 24-70mm Lens \n▪️2x Canon batteries \n▪️Charger\n▪️x1 CF Express Card 256GB\n▪️x2 64GB Sandisk Cards\n▪️Carry backpack\n\n- BOOK FOR A WEEK, ONLY PAY 4 DAYS. \n- BOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n☑️ Add any lens below for £15/day (or £75/week)\n\nRF 28-70mm f/2 L USM\nRF 24-70mm F2.8\nRF 85mm F1.2 \nRF 35mm F1.4\nRF 15-35mm F2.8\nEF 70-200 mm f/2.8 L USM\nEF 50 mm-f/1.4 USM \nEF-S 15-85mm f/3.5-5.6 IS USM\nEF-S 18-55mm f/3.5-5.6 IS\nEF 75-300mm F4.0-5.6 III \nSigma 150-500mm f5-6.3\nEF-EOS R Mount Adapter Variable ND Filter A\nGodox AD200 Pro\nGodox Xpro C Flash Trigger \nGodox V860II-C Speedlite\nTripod\nDeity V-Mic D3 Pro\n\nWe pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\nID Required\n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1961284/medium/791DBBCB-6C8D-4A09-B899-CDBA331454D2.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/704468-canon-eos-r5-rf-24-70mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: ["Canon EOS R5 + RF 24-70mm F2.8", "Canon EOS R5", "RF 24-70mm F2.8"],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "704468",
		_highlightResult: {
			title: {
				value: "Canon EOS R5 + RF 24-70mm F2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS R5 + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R5",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
		description:
			'1x Sony Alpha A7 IV\n1x Sony FE 24-105mm f/4 G OSS Lens\n1x SONY ECM-M1 SHOTGUN MICROPHONE\n1x MANFROTTO MK190 XPRO3 W. BALL HEAD\n1x NANLITE FS-150 LED DAYLIGHT SPOT LIGHT\n1x GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT\n1x KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER\n2x SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII\n1x LEXAR SD 128GB U3 V90 UHS-II R300/W260\n',
		price: 2000,
		priceExclVat: 1600,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "Jz8oFYqR9Pf-8ekzK08jvQ",
		image: "https://images.wedio.com/images/listing_images/images/1984171/medium/aegte-3.jpg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714256-video-pack-sony-a7-iv-24-108-lens-sound-lighting",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"youtube",
			"live_streaming",
			"portraits",
			"safari",
			"landscape",
			"birding",
			"food",
			"product",
			"night",
			"interviews",
			"documentary",
			"action",
			"archaeology",
			"real_estate",
			"concert",
			"journalism",
			"music_videos",
			"instagram",
			"vlogging",
			"wildlife",
			"slow_motion_video",
			"tattoo",
			"selfies",
			"large_group",
			"indoors",
			"outside",
			"high_speed_video",
			"podcast",
			"timelapse",
			"other",
		],
		productionType: "global-production-type-still-and-video",
		type: ["wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony Alpha A7 IV",
			"Sony FE 24-105mm f/4 G OSS Lens",
			"SONY ECM-M1 SHOTGUN MICROPHONE",
			"MANFROTTO MK190 XPRO3 W. BALL HEAD",
			"NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
			"GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
			'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
			"SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
			"LEXAR SD 128GB U3 V90 UHS-II R300/W260",
			"LaCie USB-C 4 TB Harddisk",
		],
		_geoloc: [
			{
				lat: 55.6924,
				lng: 12.5543,
			},
		],
		city: "Copenhagen",
		author: {
			id: "Jz8oFYqR9Pf-8ekzK08jvQ",
			name: "aegte",
			username: "aegte",
			image: "https://images.wedio.com/images/people/images/Jz8oFYqR9Pf-8ekzK08jvQ/thumb/INSTA---aegte-front-(2).png",
			country: "DK",
			vatVerified: true,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714256",
		_highlightResult: {
			title: {
				value: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 IV",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-105mm f/4 G OSS Lens",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY ECM-M1 SHOTGUN MICROPHONE",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "MANFROTTO MK190 XPRO3 W. BALL HEAD",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: 'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR SD 128GB U3 V90 UHS-II R300/W260",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LaCie USB-C 4 TB Harddisk",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "aegte",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Bell & Howell Autoload Super 8 Camera",
		description:
			"What's Included:\n\n- Bell & Howell Autoload Super 8 Camera\n- 4x AAA Batteries",
		price: 10,
		priceExclVat: 10,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "6q2q8PvHMe9GH2SdVdISfQ",
		image: "https://images.wedio.com/images/listing_images/images/1984084/medium/WhatsApp-Image-2024-02-09-at-5.05.44-pm-2.jpeg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714199-bell-howell-autoload-super-8-camera",
		categories: ["1", "9"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"documentary",
			"concert",
			"music_videos",
			"indoors",
			"outside",
			"other",
		],
		productionType: "global-production-type-video",
		brand: "other_brand",
		items: ["Bell & Howell Autoload Super 8 Camera"],
		_geoloc: {
			lat: 53.4891,
			lng: -2.27418,
		},
		author: {
			id: "6q2q8PvHMe9GH2SdVdISfQ",
			name: "Will Carswell",
			username: "williamc1",
			image: "https://images.wedio.com/images/people/images/6q2q8PvHMe9GH2SdVdISfQ/thumb/Profile-picture.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714199",
		_highlightResult: {
			title: {
				value: "Bell & Howell Autoload Super 8 Camera",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Bell & Howell Autoload Super 8 Camera",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "williamc1",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
		description:
			"Sony's flagship high-resolution-kamera med 61mp og 10-bit video-specs.\n\nAnmeldelse:\nhttps://www.youtube.com/watch?v=TqZk1zW2i1U\n\nSkriv for spørgsmål!\n\n5x Sony NP-FZ100 battery\n1x Sony A7R V\n1x LEXAR CFExpress 160GB-memory card\n1x Sony FE 24-70mm f2.8 G Master\n1x Sony FE 35mm f2.8 G Master\n1x Sony FE 20mm F1.8 G\n",
		price: 1000,
		priceExclVat: 800,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "rswuYE-4Pp5dCmv-J65dtw",
		image: "https://images.wedio.com/images/listing_images/images/1982657/medium/PSHOT-SONY-A7R-V-TOP-640PX.JPG",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/713796-sony-a7r-v-megapixel-beast-til-stills-og-8k-video-med-tre-objektiver",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"portraits",
			"astrophotography",
			"landscape",
			"birding",
			"food",
			"product",
			"documentary",
			"journalism",
			"instagram",
			"vlogging",
			"indoors",
			"outside",
		],
		productionType: "global-production-type-still-and-video",
		type: ["normal", "auto", "wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony NP-FZ100 battery",
			"Sony A7R V",
			"LEXAR CFExpress 160GB-memory card",
			"Sony FE 24-70mm f2.8 G Master",
			"Sony FE 35mm f2.8 G Master",
			"Sony FE 20mm F1.8 G",
		],
		_geoloc: {
			lat: 55.6761,
			lng: 12.5683,
		},
		city: "Copenhagen",
		author: {
			id: "rswuYE-4Pp5dCmv-J65dtw",
			name: "gemmergemmer",
			username: "gemmergemmer",
			image: "https://images.wedio.com/images/people/images/rswuYE-4Pp5dCmv-J65dtw/thumb/_DSC7301.jpg",
			country: "DK",
			vatVerified: true,
			reviews: 74,
			isPrime: false,
			feedback: 5,
		},
		objectID: "713796",
		_highlightResult: {
			title: {
				value: "Sony A7R V - megapixel beast til stills og 8k-video - med tre objektiver",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony NP-FZ100 battery",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony A7R V",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR CFExpress 160GB-memory card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-70mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 35mm f2.8 G Master",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 20mm F1.8 G",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "gemmergemmer",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Cannon C500 II 5.9 K, FULL FRAME KIT",
		description:
			"1x Cannon C500 II EF mount\n1x Otus Zeiss 3 camera lens bundle\n4x Batteries Dynacore + charger\n5x Anglebird Match Pack 512 GB  \nTilta Camera Cage for Cannon V Mount\nPL MOUNT ON DEMAND (with ULTRA PRIME objectives quality of the picture similar to ARRI cameras)\n1x Saramonic set wireless microphone\n1x Sehnheiser MKH 418 P48 Microphone\n2x  LED RAYZER MC 100 PANELS with adjustable temperatures and colours\n\nAll equipment in PELICAN and HCRP cases\n1x MANFROTTO camera stand \n\n\n\n",
		price: 400,
		priceExclVat: 400,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "EUR",
		authorId: "4b2r31AaS0PZ6IrZGFFqjA",
		image: "https://images.wedio.com/images/listing_images/images/1973330/medium/01.jpg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709375-cannon-c500-ii-5-9-k-full-frame-kit",
		categories: ["1", "2"],
		productionType: "global-production-type-still-and-video",
		items: [
			"Cannon C500 II",
			"Otus Zeiss 3 camera lens bundle",
			"Angelbird Match Pack for Canon EOS 500 512 GB ",
			"BATTERIES DYNACORE 4 PIECES + CHARGER",
			"TILTA CAMERA CAGE FOR CANNON V MOUNT",
			"SARAMONIC SET WIRELESS MICROPHONES",
			"SEHNHEISER MKH 418 P48 MICROPHONE ",
			"PL MOUNT ON DEMAND",
		],
		_geoloc: {
			lat: 52.45355,
			lng: 13.315171,
		},
		city: "Berlin",
		author: {
			id: "4b2r31AaS0PZ6IrZGFFqjA",
			name: "armanini",
			username: "armanini",
			image: "https://images.wedio.com/images/people/images/4b2r31AaS0PZ6IrZGFFqjA/thumb/data",
			country: "HR",
			vatVerified: false,
			reviews: 0,
			percentagePositive: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "709375",
		_highlightResult: {
			title: {
				value: "Cannon C500 II 5.9 K, FULL FRAME KIT",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Cannon C500 II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Otus Zeiss 3 camera lens bundle",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Angelbird Match Pack for Canon EOS 500 512 GB ",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "BATTERIES DYNACORE 4 PIECES + CHARGER",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "TILTA CAMERA CAGE FOR CANNON V MOUNT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SARAMONIC SET WIRELESS MICROPHONES",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SEHNHEISER MKH 418 P48 MICROPHONE ",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "PL MOUNT ON DEMAND",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "armanini",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS C300 MK III",
		description:
			"Canon C300 III body only. THE KIT DOES NOT ICLUDE LENS.\n\nPlease feel free to contact for a customise package or see other listing.\n\nKit includes:\n\nx1 Canon C300 III body\nx 1 Canon Professional OLED Electronic Viewfinder EVF-V704\nx1 Canon Handgrip trigger\n\nx 1 Fx lion v-mount plate\nx 2 Canon BP-A60\nx 1 Canon BP- A30\n\nx 1 Sandisk CFExpress 515GB\nx 1 Angelbird CFexpress SE Type B Card - 512GB\nx 1 CFExpress card reader",
		price: 140,
		priceExclVat: 140,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "QRUTn8VgW_HquXBwh4dHPw",
		image: "https://images.wedio.com/images/listing_images/images/1973182/medium/canon-c300-mark-iii-body-only--29045485.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709300-canon-eos-c300-mk-iii",
		categories: ["1", "2"],
		productionType: "global-production-type-video",
		brand: "canon",
		items: ["Canon EOS C300 MK III"],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "QRUTn8VgW_HquXBwh4dHPw",
			name: "Marco Beyermann Plaza",
			username: "beyermann10",
			image: "https://images.wedio.com/images/people/images/QRUTn8VgW_HquXBwh4dHPw/thumb/About-me_Portrait-2.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 1,
			percentagePositive: 100,
			isPrime: false,
			feedback: 5,
		},
		objectID: "709300",
		_highlightResult: {
			title: {
				value: "Canon EOS C300 MK III",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS C300 MK III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "beyermann10",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon R6 Mark II + RF 24-70mm",
		description:
			"Dear Fellow Creators  \n\nPLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT \n\nCollection Locations: Paddington, Holborn, Camden, Liverpool Street, Southwark, Shoreditch, Ilford or Grays.  \n\n Collection & Return Hours: 08:00 - 20:00 Mon-Sun  -\n\nDelivery Options Available\n\n Delivery £20 or Delivery and collection £30\n ☎️ WhatsApp 07506380737   \n\n Bundle Includes: \n▪️Canon EOS R6 Mark II \n▪️Canon RF 24-70mm Lens  \n▪️2x Canon batteries  \n▪️Charger \n ▪️x2 64GB Sandisk Cards\n ▪️Carry backpack  \n\n BOOK FOR A WEEK, ONLY PAY 4 DAYS.  \n\nBOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n ☑️ Add any lens below for £15/day (or £75/week)  \n\nRF 28-70mm f/2 L USM \nRF 24-70mm F2.8 \nRF 85mm F1.2  \nRF 35mm F1.4 \nRF 15-35mm F2.8 \nEF 70-200 mm f/2.8 L USM \nEF 50 mm-f/1.4 USM  \nEF-S 15-85mm f/3.5-5.6 IS USM \nEF-S 18-55mm f/3.5-5.6 IS \nEF 75-300mm F4.0-5.6 III  \nSigma 150-500mm f5-6.3 \nEF-EOS R Mount Adapter Variable ND Filter \nA Godox AD200 Pro \nGodox Xpro C Flash Trigger  \nGodox V860II-C Speedlite \nTripod \nDeity V-Mic D3 Pro \n\n We pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\n  ID Required \n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1973146/medium/1921553F-0312-4856-B48C-668494C97713.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/709291-canon-r6-mark-ii-rf-24-70mm",
		categories: ["1", "4"],
		items: [
			"Canon R6 mark II + RF 24-70mm F2.8",
			"Canon R6 Mark II",
			"Canon RF 24-70mm F2.8",
		],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "709291",
		_highlightResult: {
			title: {
				value: "Canon R6 Mark II + RF 24-70mm",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon R6 mark II + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon R6 Mark II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
		description:
			"Please ask for availability before booking.\n\nWhat's Included:\n\n- 1 * Canon Canon EOS R6 II Body\n- 2 * LP-E6NH Batteries\n- 1 * Battery Charger\n- 1 * Canon Camera Sling Strap\n- 2 * Lexar 256GB UHS-II Memory Cards\n- 1 * Camera Backpack",
		price: 29,
		priceExclVat: 24.166656,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "Mxvv6lya9KY_hxKLwu7vtg",
		image: "https://images.wedio.com/images/listing_images/images/1971255/medium/1.-Body-Only.png",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: true,
		offerShipping: true,
		offerFreeShipping: false,
		offerPickup: true,
		offerBuyNow: false,
		offerMakeOffer: true,
		gearCondition: "good",
		url: "https://www.wedio.com/listings/708430-canon-eos-r6-ii-body-only-2-batteries-2-256gb-uhs-ii-sd-cards",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: [
			" Canon EOS R6 II",
			"LP-E6NH",
			"Lexar 256GB UHS-II SD Card",
			"Canon EOS R6",
		],
		_geoloc: {
			lat: 0,
			lng: 0,
		},
		author: {
			id: "Mxvv6lya9KY_hxKLwu7vtg",
			name: "GeekyGain",
			username: "geekygain",
			image: "https://images.wedio.com/images/people/images/Mxvv6lya9KY_hxKLwu7vtg/thumb/GG-Logo-Black-(TM).png",
			country: "GB",
			vatVerified: true,
			reviews: 3,
			isPrime: false,
			feedback: 5,
		},
		objectID: "708430",
		_highlightResult: {
			title: {
				value: "Canon EOS R6 II (Body Only) + 2 Batteries + 2* 256GB UHS-II SD Cards",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: " Canon EOS R6 II",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LP-E6NH",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Lexar 256GB UHS-II SD Card",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R6",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "geekygain",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Sony A7III + Tamron 28-75mm f2.8",
		description:
			"Package includes:\n\n1x Sony A7III\n1x Tamron 28-75mm f2.8\n4x Batteries\n2x Memory cards 64GB\n\n\n\n\nMy full kit list:   \n\n- Sony A7 III  \n- Canon 80D  \n- Samyang AF 85mm F1.4 FE\n- Sigma AF 105mm f2.8\n- Tamron 28-75mm f2.8  \n- Canon EF 50mm f1.8 STM  \n- Røde VideoMic Pro \n- Røde Wireless Go + Lav Mic  \n- Zhiyun Crane Plus  \n- DJI Osmo Mobile 2  \n- Sennheiser MKE 400  \n- Hollyland Lark C1 Wireless \n",
		price: 349,
		priceExclVat: 349,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "sbCL-ROfluclifrqKt2PXg",
		image: "https://images.wedio.com/images/listing_images/images/1970260/medium/sonya7iii.jpg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/708022-sony-a7iii-tamron-28-75mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "sony",
		items: ["Sony Alpha A7 III"],
		_geoloc: [
			{
				lat: 56.146,
				lng: 10.2027,
			},
			{
				lat: 56.1895,
				lng: 10.1327,
			},
		],
		city: "Aarhus",
		author: {
			id: "sbCL-ROfluclifrqKt2PXg",
			name: "monikabara",
			username: "monikabar",
			image: "https://images.wedio.com/images/people/images/sbCL-ROfluclifrqKt2PXg/thumb/Facetune_21-08-2023-12-02-09.jpeg",
			country: "DK",
			vatVerified: false,
			reviews: 23,
			isPrime: true,
			feedback: 5,
		},
		objectID: "708022",
		_highlightResult: {
			title: {
				value: "Sony A7III + Tamron 28-75mm f2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 III",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "monikabar",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Canon EOS R5 + RF 24-70mm F2.8",
		description:
			" Dear Fellow Creators \n- PLEASE INQUIRE AVAILABILITY BEFORE BOOKING ANY EQUIPMENT ?\n\n- Collection Locations: Paddington, Holborn, Camden, Southwark, Shoreditch, Ilford or Grays. \n- Collection & Return Hours: 08:00 - 20:00 Mon-Sun \n- Delivery Options Available ? Delivery £10 or Delivery and collection £15\n☎️ WhatsApp 07506380737\n\n\n- Bundle Includes:\n▪️Canon EOS R5\n▪️Canon RF 24-70mm Lens \n▪️2x Canon batteries \n▪️Charger\n▪️x1 CF Express Card 256GB\n▪️x2 64GB Sandisk Cards\n▪️Carry backpack\n\n- BOOK FOR A WEEK, ONLY PAY 4 DAYS. \n- BOOK FOR A MONTH, ONLY PAY 12 DAYS.\n\n☑️ Add any lens below for £15/day (or £75/week)\n\nRF 28-70mm f/2 L USM\nRF 24-70mm F2.8\nRF 85mm F1.2 \nRF 35mm F1.4\nRF 15-35mm F2.8\nEF 70-200 mm f/2.8 L USM\nEF 50 mm-f/1.4 USM \nEF-S 15-85mm f/3.5-5.6 IS USM\nEF-S 18-55mm f/3.5-5.6 IS\nEF 75-300mm F4.0-5.6 III \nSigma 150-500mm f5-6.3\nEF-EOS R Mount Adapter Variable ND Filter A\nGodox AD200 Pro\nGodox Xpro C Flash Trigger \nGodox V860II-C Speedlite\nTripod\nDeity V-Mic D3 Pro\n\nWe pride ourselves in offering great customer service and check the working condition of all equipment on departure and arrival. \n\nID Required\n\n Any questions, feel free to get in touch!",
		price: 65,
		priceExclVat: 65,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "YanhisCRvxtnD6XaSjU6PQ",
		image: "https://images.wedio.com/images/listing_images/images/1961284/medium/791DBBCB-6C8D-4A09-B899-CDBA331454D2.jpeg",
		hasImage: true,
		isPromoted: true,
		isGallery: true,
		forRent: true,
		forSale: false,
		offerShipping: false,
		offerFreeShipping: false,
		offerPickup: false,
		offerBuyNow: false,
		offerMakeOffer: false,
		url: "https://www.wedio.com/listings/704468-canon-eos-r5-rf-24-70mm-f2-8",
		categories: ["1", "4"],
		productionType: "global-production-type-still-and-video",
		type: [],
		brand: "canon",
		items: ["Canon EOS R5 + RF 24-70mm F2.8", "Canon EOS R5", "RF 24-70mm F2.8"],
		_geoloc: [
			{
				lat: 51.5174,
				lng: -0.0801417,
			},
		],
		city: "London",
		author: {
			id: "YanhisCRvxtnD6XaSjU6PQ",
			name: "Mirrorless Rentals",
			username: "mirrorlessrentals",
			image: "https://images.wedio.com/images/people/images/YanhisCRvxtnD6XaSjU6PQ/thumb/4597E6EA-3D7F-437F-BFCD-991C9BB58487.png",
			country: "GB",
			vatVerified: false,
			reviews: 175,
			isPrime: true,
			feedback: 5,
		},
		objectID: "704468",
		_highlightResult: {
			title: {
				value: "Canon EOS R5 + RF 24-70mm F2.8",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Canon EOS R5 + RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Canon EOS R5",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "RF 24-70mm F2.8",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "mirrorlessrentals",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
		description:
			'1x Sony Alpha A7 IV\n1x Sony FE 24-105mm f/4 G OSS Lens\n1x SONY ECM-M1 SHOTGUN MICROPHONE\n1x MANFROTTO MK190 XPRO3 W. BALL HEAD\n1x NANLITE FS-150 LED DAYLIGHT SPOT LIGHT\n1x GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT\n1x KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER\n2x SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII\n1x LEXAR SD 128GB U3 V90 UHS-II R300/W260\n',
		price: 2000,
		priceExclVat: 1600,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "DKK",
		authorId: "Jz8oFYqR9Pf-8ekzK08jvQ",
		image: "https://images.wedio.com/images/listing_images/images/1984171/medium/aegte-3.jpg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714256-video-pack-sony-a7-iv-24-108-lens-sound-lighting",
		categories: ["1", "4"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"youtube",
			"live_streaming",
			"portraits",
			"safari",
			"landscape",
			"birding",
			"food",
			"product",
			"night",
			"interviews",
			"documentary",
			"action",
			"archaeology",
			"real_estate",
			"concert",
			"journalism",
			"music_videos",
			"instagram",
			"vlogging",
			"wildlife",
			"slow_motion_video",
			"tattoo",
			"selfies",
			"large_group",
			"indoors",
			"outside",
			"high_speed_video",
			"podcast",
			"timelapse",
			"other",
		],
		productionType: "global-production-type-still-and-video",
		type: ["wide_angle", "auto"],
		brand: "sony",
		items: [
			"Sony Alpha A7 IV",
			"Sony FE 24-105mm f/4 G OSS Lens",
			"SONY ECM-M1 SHOTGUN MICROPHONE",
			"MANFROTTO MK190 XPRO3 W. BALL HEAD",
			"NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
			"GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
			'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
			"SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
			"LEXAR SD 128GB U3 V90 UHS-II R300/W260",
			"LaCie USB-C 4 TB Harddisk",
		],
		_geoloc: [
			{
				lat: 55.6924,
				lng: 12.5543,
			},
		],
		city: "Copenhagen",
		author: {
			id: "Jz8oFYqR9Pf-8ekzK08jvQ",
			name: "aegte",
			username: "aegte",
			image: "https://images.wedio.com/images/people/images/Jz8oFYqR9Pf-8ekzK08jvQ/thumb/INSTA---aegte-front-(2).png",
			country: "DK",
			vatVerified: true,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714256",
		_highlightResult: {
			title: {
				value: "Video-pack: Sony a7 IV + 24-108 Lens + Sound + Lighting",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Sony Alpha A7 IV",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "Sony FE 24-105mm f/4 G OSS Lens",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY ECM-M1 SHOTGUN MICROPHONE",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "MANFROTTO MK190 XPRO3 W. BALL HEAD",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "NANLITE FS-150 LED DAYLIGHT SPOT LIGHT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "GODOX 60X90 CM SOFTBOX W/ GRID & BOWENS MOUNT",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: 'KUPO CT-40MK 40" MASTER C-STAND KIT  SILVER',
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "SONY NP-FZ100 BATTERY A9/II/A7RIII/IV/A7III/A7SIII",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LEXAR SD 128GB U3 V90 UHS-II R300/W260",
					matchLevel: "none",
					matchedWords: [],
				},
				{
					value: "LaCie USB-C 4 TB Harddisk",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "aegte",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
	{
		title: "Bell & Howell Autoload Super 8 Camera",
		description:
			"What's Included:\n\n- Bell & Howell Autoload Super 8 Camera\n- 4x AAA Batteries",
		price: 10,
		priceExclVat: 10,
		buyPrice: 0,
		buyPriceExclVat: 0,
		currency: "GBP",
		authorId: "6q2q8PvHMe9GH2SdVdISfQ",
		image: "https://images.wedio.com/images/listing_images/images/1984084/medium/WhatsApp-Image-2024-02-09-at-5.05.44-pm-2.jpeg",
		hasImage: true,
		isPromoted: false,
		isGallery: false,
		forRent: true,
		forSale: false,
		offerShipping: true,
		offerFreeShipping: true,
		offerPickup: true,
		offerBuyNow: true,
		offerMakeOffer: true,
		url: "https://www.wedio.com/listings/714199-bell-howell-autoload-super-8-camera",
		categories: ["1", "9"],
		goodFor: [
			"cinematography",
			"travel",
			"wedding",
			"documentary",
			"concert",
			"music_videos",
			"indoors",
			"outside",
			"other",
		],
		productionType: "global-production-type-video",
		brand: "other_brand",
		items: ["Bell & Howell Autoload Super 8 Camera"],
		_geoloc: {
			lat: 53.4891,
			lng: -2.27418,
		},
		author: {
			id: "6q2q8PvHMe9GH2SdVdISfQ",
			name: "Will Carswell",
			username: "williamc1",
			image: "https://images.wedio.com/images/people/images/6q2q8PvHMe9GH2SdVdISfQ/thumb/Profile-picture.jpg",
			country: "GB",
			vatVerified: false,
			reviews: 0,
			isPrime: false,
			feedback: 0,
		},
		objectID: "714199",
		_highlightResult: {
			title: {
				value: "Bell & Howell Autoload Super 8 Camera",
				matchLevel: "none",
				matchedWords: [],
			},
			items: [
				{
					value: "Bell & Howell Autoload Super 8 Camera",
					matchLevel: "none",
					matchedWords: [],
				},
			],
			author: {
				username: {
					value: "williamc1",
					matchLevel: "none",
					matchedWords: [],
				},
			},
		},
	},
];

export async function GET(request: NextRequest) {
	// const type = request.nextUrl.searchParams.get("type");
	// const listingsArr = listings.filter((listing: any) => {
	// 	if (type === "buy") {
	// 		return listing.forSale === true;
	// 	}
	// 	return listing.forRent === true;
	// });
	return NextResponse.json(listings);
}
